config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :messages, only: [:new, :create]
  resources :pictures
  resources :tags, only: [:index, :show]
  get 'main/index'
  get 'post/like_change'
  get 'all_posts' => 'posts#all_posts'
  post 'posts_like_change' => 'posts#posts_like_change', as: 'posts_like_change'
  post 'comments_like_change' => 'comments#comments_like_change', as: 'comments_like_change'

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :posts

  end 

  resources :posts do
    resources :comments

  end    

  root 'main#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :comment_likes, dependent: :destroy

  has_ancestry
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_action :authenticate_user!, only: [:create, :new]

  def new
    @comment = Comment.new(:parent_id => params[:parent_id])
    @parent_id = params[:parent_id]
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post_id = comment_params[:post_id]

    if @comment.save
      flash[:success] = 'Комментарий успешно добавлен'
      redirect_to user_post_path(current_user.id, comment_params[:post_id])
    else
      render :new
    end
  end

  def comments_like_change
    like = CommentLike.where(user_id: current_user.id, comment_id: params[:comment_id])

    if like.count > 0
      flash[:success] = 'Лайк удалён'
      like.first.destroy
    else
      flash[:success] = 'Лайк добавлен'
      CommentLike.create(user_id: current_user.id, comment_id: params[:comment_id])
    end

    redirect_to :back
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :parent_id, :post_id, :comment_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |message, sub_comments|
      render(message) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end  

  def comment_like(comment_id)
    return CommentLike.where(comment_id: comment_id).count
  end

  def comment_author(comment_id)
    comment = Comment.find(comment_id)
    return User.find(comment.user_id)
  end
end

app/views/comments/_comment.html.erb
<div class="comment panel panel-default">
  <div class="body panel-body">
    <%= comment.body %>
  </div>

  <div class="actions panel-footer" style="overflow: hidden;">
    <div class="author_label_area pull-left">  
      <strong>author:</strong>
      <%= comment.user.title %> 
      <small>(<%= mail_to comment_author(comment.id).email, comment_author(comment.id).email %>)</small>
    </div>

    <div class="comments_likes_area pull-right">    
      <strong>likes:</strong>      

      <%= form_tag(comments_like_change_path, method: :post, class: 'inline_block' )do %>
        <%= hidden_field_tag(:comment_id, comment.id) %>
        <span><%= comment_like(comment.id) %></span>

        <% if user_signed_in? %>
          <%= submit_tag 'Проголосовать', class: 'btn-sm btn-info' %>
        <% end %>

      <% end %>      
    </div>

    <% if user_signed_in? %>
      <%= link_to 'reply', new_post_comment_path(:post_id => @post.id, :parent_id => comment), class: 'pull-right' %>
    <% end %>    
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :post_id, value: @post.id %>

  <%= f.hidden_field :parent_id, value: @parent_id %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>