config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :messages, only: [:new, :create]
  resources :pictures
  resources :tags, only: [:index, :show]
  get 'main/index'
  get 'post/like_change'
  get 'all_posts' => 'posts#all_posts'
  post 'posts_like_change' => 'posts#posts_like_change', as: 'posts_like_change'
  post 'comments_like_change' => 'comments#comments_like_change', as: 'comments_like_change'

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :posts

  end 

  resources :posts do
    resources :comments

  end    

  root 'main#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :post_status
  belongs_to :user
  has_many :post_likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags

  validates :title, presence: true, length: { maximum:  600, minimum: 3 }
  validates :body, presence: true, length: { maximum:  60000, minimum: 100 }
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_active_user!, only: [:create, :edit, :update, :destroy]
  before_action :owner_post_or_admin_check, only: [:edit, :update, :destroy]

  def index
    @posts = Post.where(id: params[:id], post_status_id: 1).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @comment = Comment.new
    @comments = Comment.where(post_id: @post.id)#.paginate(page: params[:page], :per_page => 6)
    @post_likes_count = PostLike.where(post_id: @post.id).count
    @tags = @post.tags

    # generate comment ability notice
    unless user_signed_in?
      @notice_comment_ability = 'Добавлять комментарии могут только авторизованные пользователи'
    end    
  end

  def new
    @post = Post.new
  end

  def edit
    @tags = @post.tags
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save    
      add_new_tags(@post)  
      flash[:success] = 'Пост успешно создан'
      redirect_to @post
    else
      flash.now[:error] = 'При создании поста произошла ошибка'
      render :new 
    end
  end

=begin
  def update
    begin  
      p 22222222222222222222222222222222222222222
      p post_params 
      p post_params[:title]
      @post.update(post_params)
      p @post
      add_new_tags(@post) if params[:tagnames]
      destroy_tags(params['delete_tags'], @post) if params['delete_tags']   
      flash[:success] = 'Пост успешно обновлён'
      redirect_to user_post_path(current_user.id, @post.id)
    rescue  
      p 33333333333333333333333333333333333333333333
      logger.debug 'update post is failed'
      flash.now[:error] = 'При обновлении поста произошла ошибка'
      render :edit
    end
  end
=end

  def update
    if @post.update(post_params)
      add_new_tags(@post) if params[:tagnames]  
      destroy_tags(params['delete_tags'], @post) if params['delete_tags']    
      flash[:success] = 'Пост успешно обновлён'
      redirect_to user_post_path(current_user.id, @post.id)
    else
      flash.now[:error] = 'При обновлении поста произошла ошибка'
      render :edit
    end
  end

  def destroy(real_delete = false)
    if @post.update(post_status_id: 2)
      flash[:success] = 'Пост успешно удалён'
      redirect_to all_posts_path
    end

    if real_delete == true
      @post.destroy
      flash[:success] = 'Пост успешно удалён из БД'
      redirect_to all_posts_path
    end
  end

  def posts_like_change
    like = PostLike.where(user_id: current_user.id, post_id: params[:post_id])

    if like.count > 0
      like.first.destroy
    else
      PostLike.create(user_id: current_user.id, post_id: params[:post_id])
    end

    redirect_to :back
  end

  def all_posts
    @posts = Post.where(post_status_id: 1).paginate(page: params[:page], :per_page => 10).order(created_at: :desc)
    @post = Post.new
  end

  private
    def set_post
      @post = Post.where(id: params[:id], post_status_id: 1).first
      error_404 unless @post
    end

    def post_params
      params.require(:post).permit(:title, :body, :post_id, :tagnames)
    end

    def owner_post_or_admin_check
      unless (current_user.id == @post.user_id) || (current_user.superadmin == true)
        error_403 unless current_user.id == @post.user_id   
      end
    end 
    
    def add_new_tags(post)
      tagnames = params[:tagnames].split(/[, \.?!]+/)
      tagnames.each do |tagname|
        tag = Tag.find_by(title: tagname.downcase)
        if tag
          sql = "select * from 'posts_tags' where post_id = #{post.id} and tag_id = #{tag.id}"
          records_array = ActiveRecord::Base.connection.execute(sql) 
          tag.posts << post if records_array.count == 0  
        else
          tag = Tag.create(title: tagname.downcase)  
          tag.posts << post     
        end
      end
    end  

    def destroy_tags(tags,post)
      tags.each do |tag|   
        sql = "delete from 'posts_tags' where post_id = #{post.id} and tag_id = #{tag}"
        records_array = ActiveRecord::Base.connection.execute(sql)    
      end
    end 

=begin
    def add_new_tags(post)
      tagnames = params[:tagnames].split(/[, \.?!]+/) 
      tagnames.each do |tagname|
        tag = Tag.find_by(title: tagname.downcase)
        if tag
          sql = "select * from 'posts_tags' where post_id = #{post.id} and tag_id = #{tag.id}"

          begin
            records_array = ActiveRecord::Base.connection.execute(sql)     
            tag.posts << post if records_array.count == 0
          rescue
            logger.debug 'query for add association posts_tags is failed'
            raise 'add_new_tags error'
          end
        else
          begin
            tag = Tag.create(title: tagname.downcase)
            tag.posts << post
          rescue
            logger.debug 'query for create tag and add association posts_tags is failed'
            raise 'add_new_tags error'
          end
        end
      end
    end  

    def destroy_tags(tags,post)
      tags.each do |tag|
        sql = "delete from 'posts_tags' where post_id = #{post.id} and tag_id = #{tag}"

        unless ActiveRecord::Base.connection.execute(sql)  
          logger.debug 'query for delete tags is failed'
          raise 'destroy_tags error'          
        end
      end
    end  
=end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div class="tags_area">
    <%= text_field_tag 'tagnames', nil, class: 'tagnames' %>
    <div class="help_phrase">Введите теги через запятую</div>
  </div>

  <div class="edit_tags_area">
    <% if @tags && @tags.count > 0 %>
      <div class="row">
        <div class="col-xs-12 col-sm-2">
          <label class="lbl_tagname"><%= t :delete_tags %>: </label>
        </div>
        <div class="col-xs-12 col-sm-10">
          <div class="row">
            <% @tags.each do |tag|%>
              <div class="col-xs-6 col-sm-4">
                <%= check_box_tag("delete_tags[]", tag.id) %>
                <%= label_tag(:delete_tags, tag.title) %>
              </div>
            <% end %>
          </div>
        </div>
      </div>   
    <% end %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/all_posts.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <h2>Создать пост</h2>
  <%= render 'form' %>
<% end %>

<h1>Listing all Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.body, length: 170)  %></td>
        <td><%= link_to 'Show', user_post_path(post.user_id, post.id) %></td>
        <td><%= link_to 'edit', edit_user_post_path(post.user_id, post.id) if user_signed_in? %></td>
        <td><%= link_to 'delete', user_post_path(post.user_id, post.id), method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<%= link_to 'New Post', new_post_path %>
<br />
<br />

<table>
  <thead>
    <tr>
      <th>Title/</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div><%= link_to 'edit', edit_user_post_path(@post.user_id, @post.id) if user_signed_in? %></div>
<div><%= link_to 'delete', user_post_path(@post.user_id, @post.id), method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? %></div>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div class="tags_area">
  <strong>Tags: </strong>
  <% @tags.each do |tag| %>
    <%= link_to tag.title, tag_path(tag.id), class: 'tag_link' %>
  <% end %>
</div>

<p>
  <strong>likes:</strong>

  <%= form_tag(posts_like_change_path, method: :post, class: 'pull-left') do %>
    <%= hidden_field_tag(:post_id, @post.id) %>
    <span><%= @post_likes_count %> </span>

    <% if user_signed_in? %>
      <%= submit_tag 'Проголосовать', class: 'btn-sm btn-info' %>
    <% end %>

  <% end %>
</p>


<br />
<br />
<br />

<div class="comments_area">
  <%= @notice_comment_ability %>
  
  <% if @comment && user_signed_in? %>
    <%= form_for [@post, @comment] do |f| %>
      <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.hidden_field :parent_id %>
      <%= f.hidden_field :post_id, :value => @post.id %>

      <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  <% end %>

  <br />

  <%= nested_comments @comments.arrange(:order => :created_at) %>

  <%#= will_paginate @comments %>
</div>