config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :messages, only: [:new, :create]
  resources :pictures
  resources :tags, only: [:index, :show]
  get 'main/index'
  get 'post/like_change'
  get 'all_posts' => 'posts#all_posts'
  post 'posts_like_change' => 'posts#posts_like_change', as: 'posts_like_change'
  post 'comments_like_change' => 'comments#comments_like_change', as: 'comments_like_change'

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :posts

  end 

  resources :posts do
    resources :comments

  end    

  root 'main#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :comment_likes, dependent: :destroy

  has_ancestry
end

app/models/comment_like.rb
class CommentLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment  
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, presence: true, length: { maximum:  600, minimum: 10 }
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :post_status
  belongs_to :user
  has_many :post_likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags

  validates :title, presence: true, length: { maximum:  600, minimum: 3 }
  validates :body, presence: true, length: { maximum:  60000, minimum: 100 }
end

app/models/post_like.rb
class PostLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post_status.rb
class PostStatus < ActiveRecord::Base
  has_many :posts
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  belongs_to :user_status
  has_many :post_likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum:  40, minimum: 2 }
end

app/models/user_status.rb
class UserStatus < ActiveRecord::Base
  has_many :users
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]

  def index
    @tags = Tag.all.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @posts = @tag.posts.paginate(page: params[:page], :per_page => 10)
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params[:tag]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |message, sub_comments|
      render(message) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end  

  def comment_like(comment_id)
    return CommentLike.where(comment_id: comment_id).count
  end

  def comment_author(comment_id)
    comment = Comment.find(comment_id)
    return User.find(comment.user_id)
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>&copy; Company 2014</p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>Blogolog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<div class="masthead">
  <div class="row">
    <div class="col-sx-12 col-sm-6">
      <h3 class="text-muted">Blogolog</h3>
    </div>

    <div class="col-sx-12 col-sm-6">
      <h3 class="pull-right">
        <% if user_signed_in? %>
            <span>Здравствуйте, <%= link_to current_user.title, user_path(current_user.id) %></span>
            <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
        <% else %>
            <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
        <% end %>  
      </h3>  
    </div>  
  </div>  

  <nav>
    <ul class="nav nav-justified">
      <li><%= link_to 'main',  main_index_path %></li>
      <li><%= link_to 'blog',  all_posts_path %></li>
      <li><%= link_to 'tags',  tags_path %></li>
      <li><%= link_to 'gallery',  pictures_path %></li>
      <li><%= link_to 'feedback',  new_message_path %></li>
      <li><%= link_to 'users',  users_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_notice_area.html.erb
<div class="notice_area">
  <% flash.each do |message_type,  message| %>
    <div class="alert  alert-<%= message_type %>" id="alertMessage"><%= message %></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="ru">
  <%= render 'layouts/head' %>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <%= render 'layouts/notice_area' %>    

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>